### ISSUE TITLE
dmat compiles to mat

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#161] opened 2018-01-17 18:11 UTC
All dmats compile to mats!

`:dmat2x3` compiles `"mat2x3"`

etc

**Comment by cbaggers** [comment] 2018-01-18 09:01
```
(glsl-code
 (compile-frag nil :450 nil
   (let (((a :dmat3)))
	 (v! 1 2 3 4))))
"// fragment-stage
#version 450

layout(location = 0)  out vec4 _FRAGMENT_STAGE_OUT_0;

void main()
{
    dmat3 A;
    vec4 g_GEXPR0_1129 = vec4(float(1),float(2),float(3),float(4));
    _FRAGMENT_STAGE_OUT_0 = g_GEXPR0_1129;
    return;
}
"
```
Better.

**Comment by cbaggers** [comment] 2018-01-18 09:05
Should be fixed on master now. One problem you are going to run into almost immediately is that there are no functions defined that take a `:mat2x3`.

The issue is that the operators in glsl are not defined in the man pages as so are not in glsl-spec. This has meant I have been slowly adding them here https://github.com/cbaggers/varjo/blob/master/src/vari.glsl/functions.lisp but it's a slow adhoc process. At some point I want to generate the full selection of operator specifications and add them to glsl-spec. At that point varjo will pick them up automatically and we can get rid of many of these extra definitions.

Sorry for the hackiness of this

**Closed by cbaggers** 2018-01-18 09:05 UTC
